- hosts: all
  become: yes

  - apt: pkg={{item}} state=present
    with_items:
      - git-core

#  - shell: git clone git://git.drogon.net/wiringPi
#  - shell: ./build

  #apt-get install python-dev

  #pip install spidev
  #pip install wiringPi ??

  #ja sit enable raspi-configista spidev

## lol.py
# import spidev
# import time
#
# adc_channel = 0
# spi = spidev.SpiDev()
# spi.open(0,0)
#
# def readadc(adcnum):
# # read SPI data from MCP3004 chip, 4 possible adc's (0 thru 3)
#   if adcnum >3 or adcnum <0:
#      return-1
#   r = spi.xfer2([1,8+adcnum <<4,0])
#   adcout = ((r[1] &3) <<8)+r[2]
#   return adcout
#
# #while True:
#
# value=readadc(adc_channel)
# volts=(value*3.3)/1024
# print("%4d/1023 => %5.3f V" % (value, volts))
# print((volts-0.5)*100)

#    time.sleep(0.5)
